"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Phalanx ACT_BB_R_C3_T2 0.2 0.34"
	}
	"phalanx"
	{
		"ACT_BB_R_C3_T2"
		{
			"trace"
			{
				"cycle"		"0.201250"
			}
			"trace"
			{
				"cycle"		"0.206250"
			}
			"trace"
			{
				"cycle"		"0.211250"
			}
			"trace"
			{
				"cycle"		"0.216250"
			}
			"trace"
			{
				"cycle"		"0.263750"
			}
			"trace"
			{
				"cycle"		"0.280000"
			}
			"trace"
			{
				"cycle"		"0.307500"
			}
		}
	}
}
