"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Vanguard ACT_BB_H_RIGHT_T2 0.12 0.8"
	}
	"vanguard"
	{
		"ACT_BB_H_RIGHT_T2"
		{
			"trace"
			{
				"cycle"		"0.120000"
			}
			"trace"
			{
				"cycle"		"0.127500"
			}
			"trace"
			{
				"cycle"		"0.132500"
			}
			"trace"
			{
				"cycle"		"0.138750"
			}
			"trace"
			{
				"cycle"		"0.145000"
			}
			"trace"
			{
				"cycle"		"0.151250"
			}
			"trace"
			{
				"cycle"		"0.160000"
			}
			"trace"
			{
				"cycle"		"0.168750"
			}
			"trace"
			{
				"cycle"		"0.176251"
			}
			"trace"
			{
				"cycle"		"0.181250"
			}
			"trace"
			{
				"cycle"		"0.186250"
			}
			"trace"
			{
				"cycle"		"0.192500"
			}
			"trace"
			{
				"cycle"		"0.198751"
			}
			"trace"
			{
				"cycle"		"0.203751"
			}
			"trace"
			{
				"cycle"		"0.207500"
			}
			"trace"
			{
				"cycle"		"0.211250"
			}
			"trace"
			{
				"cycle"		"0.215000"
			}
			"trace"
			{
				"cycle"		"0.218751"
			}
			"trace"
			{
				"cycle"		"0.223750"
			}
			"trace"
			{
				"cycle"		"0.228750"
			}
			"trace"
			{
				"cycle"		"0.233750"
			}
			"trace"
			{
				"cycle"		"0.238750"
			}
			"trace"
			{
				"cycle"		"0.243750"
			}
			"trace"
			{
				"cycle"		"0.248750"
			}
			"trace"
			{
				"cycle"		"0.253750"
			}
			"trace"
			{
				"cycle"		"0.257500"
			}
			"trace"
			{
				"cycle"		"0.261251"
			}
			"trace"
			{
				"cycle"		"0.266250"
			}
			"trace"
			{
				"cycle"		"0.271250"
			}
			"trace"
			{
				"cycle"		"0.276250"
			}
			"trace"
			{
				"cycle"		"0.280001"
			}
			"trace"
			{
				"cycle"		"0.283751"
			}
			"trace"
			{
				"cycle"		"0.287501"
			}
			"trace"
			{
				"cycle"		"0.291250"
			}
			"trace"
			{
				"cycle"		"0.295000"
			}
			"trace"
			{
				"cycle"		"0.298751"
			}
			"trace"
			{
				"cycle"		"0.302501"
			}
			"trace"
			{
				"cycle"		"0.305000"
			}
			"trace"
			{
				"cycle"		"0.307501"
			}
			"trace"
			{
				"cycle"		"0.310000"
			}
			"trace"
			{
				"cycle"		"0.312501"
			}
			"trace"
			{
				"cycle"		"0.315000"
			}
			"trace"
			{
				"cycle"		"0.318750"
			}
			"trace"
			{
				"cycle"		"0.322501"
			}
			"trace"
			{
				"cycle"		"0.326251"
			}
			"trace"
			{
				"cycle"		"0.332500"
			}
			"trace"
			{
				"cycle"		"0.340001"
			}
			"trace"
			{
				"cycle"		"0.347500"
			}
			"trace"
			{
				"cycle"		"0.355001"
			}
			"trace"
			{
				"cycle"		"0.362501"
			}
			"trace"
			{
				"cycle"		"0.371250"
			}
			"trace"
			{
				"cycle"		"0.380000"
			}
			"trace"
			{
				"cycle"		"0.386251"
			}
			"trace"
			{
				"cycle"		"0.392501"
			}
			"trace"
			{
				"cycle"		"0.398750"
			}
			"trace"
			{
				"cycle"		"0.407501"
			}
			"trace"
			{
				"cycle"		"0.415001"
			}
			"trace"
			{
				"cycle"		"0.422500"
			}
			"trace"
			{
				"cycle"		"0.431251"
			}
			"trace"
			{
				"cycle"		"0.440001"
			}
			"trace"
			{
				"cycle"		"0.448751"
			}
			"trace"
			{
				"cycle"		"0.458751"
			}
			"trace"
			{
				"cycle"		"0.468751"
			}
			"trace"
			{
				"cycle"		"0.480001"
			}
			"trace"
			{
				"cycle"		"0.492501"
			}
			"trace"
			{
				"cycle"		"0.508751"
			}
			"trace"
			{
				"cycle"		"0.518751"
			}
			"trace"
			{
				"cycle"		"0.527501"
			}
			"trace"
			{
				"cycle"		"0.532501"
			}
			"trace"
			{
				"cycle"		"0.536251"
			}
			"trace"
			{
				"cycle"		"0.540000"
			}
			"trace"
			{
				"cycle"		"0.543750"
			}
			"trace"
			{
				"cycle"		"0.547501"
			}
			"trace"
			{
				"cycle"		"0.551251"
			}
			"trace"
			{
				"cycle"		"0.555001"
			}
			"trace"
			{
				"cycle"		"0.558750"
			}
			"trace"
			{
				"cycle"		"0.562500"
			}
			"trace"
			{
				"cycle"		"0.566250"
			}
			"trace"
			{
				"cycle"		"0.570001"
			}
			"trace"
			{
				"cycle"		"0.573751"
			}
			"trace"
			{
				"cycle"		"0.578751"
			}
			"trace"
			{
				"cycle"		"0.585000"
			}
			"trace"
			{
				"cycle"		"0.590000"
			}
			"trace"
			{
				"cycle"		"0.595000"
			}
			"trace"
			{
				"cycle"		"0.600000"
			}
			"trace"
			{
				"cycle"		"0.607500"
			}
			"trace"
			{
				"cycle"		"0.614999"
			}
			"trace"
			{
				"cycle"		"0.622500"
			}
			"trace"
			{
				"cycle"		"0.636250"
			}
			"trace"
			{
				"cycle"		"0.652499"
			}
			"trace"
			{
				"cycle"		"0.667500"
			}
			"trace"
			{
				"cycle"		"0.683749"
			}
			"trace"
			{
				"cycle"		"0.701249"
			}
			"trace"
			{
				"cycle"		"0.726249"
			}
			"trace"
			{
				"cycle"		"0.786249"
			}
		}
	}
}
