"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Knight ACT_BB_H_LEFT_T2 0.26 0.3"
	}
	"knight"
	{
		"ACT_BB_H_LEFT_T2"
		{
			"trace"
			{
				"cycle"		"0.260034"
			}
			"trace"
			{
				"cycle"		"0.262934"
			}
			"trace"
			{
				"cycle"		"0.265834"
			}
			"trace"
			{
				"cycle"		"0.268734"
			}
			"trace"
			{
				"cycle"		"0.278400"
			}
			"trace"
			{
				"cycle"		"0.294834"
			}
		}
	}
}
