"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Ryoku ACT_BB_R_C1_T1 0.155 0.19"
	}
	"ryoku"
	{
		"ACT_BB_R_C1_T1"
		{
			"trace"
			{
				"cycle"		"0.155000"
			}
			"trace"
			{
				"cycle"		"0.159999"
			}
			"trace"
			{
				"cycle"		"0.164999"
			}
			"trace"
			{
				"cycle"		"0.170000"
			}
			"trace"
			{
				"cycle"		"0.175000"
			}
			"trace"
			{
				"cycle"		"0.181667"
			}
			"trace"
			{
				"cycle"		"0.188333"
			}
		}
	}
}
