"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Ryoku ACT_BB_R_C2_T1 0.17 0.19"
	}
	"ryoku"
	{
		"ACT_BB_R_C2_T1"
		{
			"trace"
			{
				"cycle"		"0.170502"
			}
			"trace"
			{
				"cycle"		"0.174168"
			}
			"trace"
			{
				"cycle"		"0.177834"
			}
			"trace"
			{
				"cycle"		"0.181503"
			}
			"trace"
			{
				"cycle"		"0.185169"
			}
			"trace"
			{
				"cycle"		"0.188834"
			}
		}
	}
}
