"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Ryoku ACT_BB_A_RIGHT_T1 0.2 0.7"
	}
	"ryoku"
	{
		"ACT_BB_A_RIGHT_T1"
		{
			"trace"
			{
				"cycle"		"0.200000"
			}
			"trace"
			{
				"cycle"		"0.205000"
			}
			"trace"
			{
				"cycle"		"0.210001"
			}
			"trace"
			{
				"cycle"		"0.215000"
			}
			"trace"
			{
				"cycle"		"0.220000"
			}
			"trace"
			{
				"cycle"		"0.223334"
			}
			"trace"
			{
				"cycle"		"0.226666"
			}
			"trace"
			{
				"cycle"		"0.230000"
			}
			"trace"
			{
				"cycle"		"0.233333"
			}
			"trace"
			{
				"cycle"		"0.236667"
			}
			"trace"
			{
				"cycle"		"0.240000"
			}
			"trace"
			{
				"cycle"		"0.243334"
			}
			"trace"
			{
				"cycle"		"0.246666"
			}
			"trace"
			{
				"cycle"		"0.250000"
			}
			"trace"
			{
				"cycle"		"0.255000"
			}
			"trace"
			{
				"cycle"		"0.260001"
			}
			"trace"
			{
				"cycle"		"0.264999"
			}
			"trace"
			{
				"cycle"		"0.271666"
			}
			"trace"
			{
				"cycle"		"0.278334"
			}
			"trace"
			{
				"cycle"		"0.286667"
			}
			"trace"
			{
				"cycle"		"0.295000"
			}
			"trace"
			{
				"cycle"		"0.303334"
			}
			"trace"
			{
				"cycle"		"0.311667"
			}
			"trace"
			{
				"cycle"		"0.318333"
			}
			"trace"
			{
				"cycle"		"0.325000"
			}
			"trace"
			{
				"cycle"		"0.331666"
			}
			"trace"
			{
				"cycle"		"0.341667"
			}
			"trace"
			{
				"cycle"		"0.353334"
			}
			"trace"
			{
				"cycle"		"0.364999"
			}
			"trace"
			{
				"cycle"		"0.378334"
			}
			"trace"
			{
				"cycle"		"0.393333"
			}
			"trace"
			{
				"cycle"		"0.408332"
			}
			"trace"
			{
				"cycle"		"0.421666"
			}
			"trace"
			{
				"cycle"		"0.433332"
			}
			"trace"
			{
				"cycle"		"0.443333"
			}
			"trace"
			{
				"cycle"		"0.453334"
			}
			"trace"
			{
				"cycle"		"0.461666"
			}
			"trace"
			{
				"cycle"		"0.469999"
			}
			"trace"
			{
				"cycle"		"0.478333"
			}
			"trace"
			{
				"cycle"		"0.486666"
			}
			"trace"
			{
				"cycle"		"0.493333"
			}
			"trace"
			{
				"cycle"		"0.499999"
			}
			"trace"
			{
				"cycle"		"0.506666"
			}
			"trace"
			{
				"cycle"		"0.513332"
			}
			"trace"
			{
				"cycle"		"0.519999"
			}
			"trace"
			{
				"cycle"		"0.526666"
			}
			"trace"
			{
				"cycle"		"0.531666"
			}
			"trace"
			{
				"cycle"		"0.536666"
			}
			"trace"
			{
				"cycle"		"0.541666"
			}
			"trace"
			{
				"cycle"		"0.546665"
			}
			"trace"
			{
				"cycle"		"0.551665"
			}
			"trace"
			{
				"cycle"		"0.556666"
			}
			"trace"
			{
				"cycle"		"0.561666"
			}
			"trace"
			{
				"cycle"		"0.566666"
			}
			"trace"
			{
				"cycle"		"0.571665"
			}
			"trace"
			{
				"cycle"		"0.576665"
			}
			"trace"
			{
				"cycle"		"0.581666"
			}
			"trace"
			{
				"cycle"		"0.586666"
			}
			"trace"
			{
				"cycle"		"0.591666"
			}
			"trace"
			{
				"cycle"		"0.596665"
			}
			"trace"
			{
				"cycle"		"0.601665"
			}
			"trace"
			{
				"cycle"		"0.606666"
			}
			"trace"
			{
				"cycle"		"0.611666"
			}
			"trace"
			{
				"cycle"		"0.616666"
			}
			"trace"
			{
				"cycle"		"0.621665"
			}
			"trace"
			{
				"cycle"		"0.626665"
			}
			"trace"
			{
				"cycle"		"0.631665"
			}
			"trace"
			{
				"cycle"		"0.636666"
			}
			"trace"
			{
				"cycle"		"0.641666"
			}
			"trace"
			{
				"cycle"		"0.646665"
			}
			"trace"
			{
				"cycle"		"0.651665"
			}
			"trace"
			{
				"cycle"		"0.656665"
			}
			"trace"
			{
				"cycle"		"0.661666"
			}
			"trace"
			{
				"cycle"		"0.666666"
			}
			"trace"
			{
				"cycle"		"0.671665"
			}
			"trace"
			{
				"cycle"		"0.676665"
			}
			"trace"
			{
				"cycle"		"0.681665"
			}
			"trace"
			{
				"cycle"		"0.686666"
			}
			"trace"
			{
				"cycle"		"0.691666"
			}
			"trace"
			{
				"cycle"		"0.696665"
			}
		}
	}
}
