"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Ryoku ACT_BB_A_C2_T1 0.65 0.9"
	}
	"ryoku"
	{
		"ACT_BB_A_C2_T1"
		{
			"trace"
			{
				"cycle"		"0.651561"
			}
			"trace"
			{
				"cycle"		"0.671874"
			}
			"trace"
			{
				"cycle"		"0.701563"
			}
			"trace"
			{
				"cycle"		"0.750000"
			}
			"trace"
			{
				"cycle"		"0.810937"
			}
			"trace"
			{
				"cycle"		"0.862498"
			}
		}
	}
}
