"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_RIGHT_T2 0.3 0.85"
	}
	"pure"
	{
		"ACT_BB_B_RIGHT_T2"
		{
			"trace"
			{
				"cycle"		"0.300513"
			}
			"trace"
			{
				"cycle"		"0.305641"
			}
			"trace"
			{
				"cycle"		"0.309744"
			}
			"trace"
			{
				"cycle"		"0.313846"
			}
			"trace"
			{
				"cycle"		"0.317949"
			}
			"trace"
			{
				"cycle"		"0.322051"
			}
			"trace"
			{
				"cycle"		"0.326153"
			}
			"trace"
			{
				"cycle"		"0.330256"
			}
			"trace"
			{
				"cycle"		"0.334358"
			}
			"trace"
			{
				"cycle"		"0.339487"
			}
			"trace"
			{
				"cycle"		"0.344615"
			}
			"trace"
			{
				"cycle"		"0.351794"
			}
			"trace"
			{
				"cycle"		"0.360000"
			}
			"trace"
			{
				"cycle"		"0.368204"
			}
			"trace"
			{
				"cycle"		"0.375384"
			}
			"trace"
			{
				"cycle"		"0.380512"
			}
			"trace"
			{
				"cycle"		"0.385640"
			}
			"trace"
			{
				"cycle"		"0.390769"
			}
			"trace"
			{
				"cycle"		"0.395896"
			}
			"trace"
			{
				"cycle"		"0.399999"
			}
			"trace"
			{
				"cycle"		"0.404102"
			}
			"trace"
			{
				"cycle"		"0.408204"
			}
			"trace"
			{
				"cycle"		"0.412307"
			}
			"trace"
			{
				"cycle"		"0.416409"
			}
			"trace"
			{
				"cycle"		"0.420512"
			}
			"trace"
			{
				"cycle"		"0.424614"
			}
			"trace"
			{
				"cycle"		"0.428717"
			}
			"trace"
			{
				"cycle"		"0.432820"
			}
			"trace"
			{
				"cycle"		"0.436922"
			}
			"trace"
			{
				"cycle"		"0.442050"
			}
			"trace"
			{
				"cycle"		"0.447178"
			}
			"trace"
			{
				"cycle"		"0.451281"
			}
			"trace"
			{
				"cycle"		"0.455383"
			}
			"trace"
			{
				"cycle"		"0.459486"
			}
			"trace"
			{
				"cycle"		"0.463589"
			}
			"trace"
			{
				"cycle"		"0.466665"
			}
			"trace"
			{
				"cycle"		"0.469742"
			}
			"trace"
			{
				"cycle"		"0.472819"
			}
			"trace"
			{
				"cycle"		"0.475896"
			}
			"trace"
			{
				"cycle"		"0.478973"
			}
			"trace"
			{
				"cycle"		"0.482050"
			}
			"trace"
			{
				"cycle"		"0.485127"
			}
			"trace"
			{
				"cycle"		"0.488203"
			}
			"trace"
			{
				"cycle"		"0.491280"
			}
			"trace"
			{
				"cycle"		"0.494358"
			}
			"trace"
			{
				"cycle"		"0.497434"
			}
			"trace"
			{
				"cycle"		"0.501537"
			}
			"trace"
			{
				"cycle"		"0.505639"
			}
			"trace"
			{
				"cycle"		"0.509742"
			}
			"trace"
			{
				"cycle"		"0.516921"
			}
			"trace"
			{
				"cycle"		"0.526152"
			}
			"trace"
			{
				"cycle"		"0.532306"
			}
			"trace"
			{
				"cycle"		"0.538459"
			}
			"trace"
			{
				"cycle"		"0.543588"
			}
			"trace"
			{
				"cycle"		"0.548716"
			}
			"trace"
			{
				"cycle"		"0.553844"
			}
			"trace"
			{
				"cycle"		"0.558972"
			}
			"trace"
			{
				"cycle"		"0.563075"
			}
			"trace"
			{
				"cycle"		"0.569228"
			}
			"trace"
			{
				"cycle"		"0.575382"
			}
			"trace"
			{
				"cycle"		"0.586664"
			}
			"trace"
			{
				"cycle"		"0.594869"
			}
			"trace"
			{
				"cycle"		"0.599997"
			}
			"trace"
			{
				"cycle"		"0.604100"
			}
			"trace"
			{
				"cycle"		"0.607177"
			}
			"trace"
			{
				"cycle"		"0.611279"
			}
			"trace"
			{
				"cycle"		"0.615382"
			}
			"trace"
			{
				"cycle"		"0.619485"
			}
			"trace"
			{
				"cycle"		"0.624613"
			}
			"trace"
			{
				"cycle"		"0.630766"
			}
			"trace"
			{
				"cycle"		"0.638972"
			}
			"trace"
			{
				"cycle"		"0.650254"
			}
			"trace"
			{
				"cycle"		"0.660510"
			}
			"trace"
			{
				"cycle"		"0.668715"
			}
			"trace"
			{
				"cycle"		"0.674869"
			}
			"trace"
			{
				"cycle"		"0.679997"
			}
			"trace"
			{
				"cycle"		"0.685125"
			}
			"trace"
			{
				"cycle"		"0.690253"
			}
			"trace"
			{
				"cycle"		"0.695381"
			}
			"trace"
			{
				"cycle"		"0.699484"
			}
			"trace"
			{
				"cycle"		"0.704612"
			}
			"trace"
			{
				"cycle"		"0.709740"
			}
			"trace"
			{
				"cycle"		"0.714868"
			}
			"trace"
			{
				"cycle"		"0.719997"
			}
			"trace"
			{
				"cycle"		"0.726150"
			}
			"trace"
			{
				"cycle"		"0.732304"
			}
			"trace"
			{
				"cycle"		"0.738458"
			}
			"trace"
			{
				"cycle"		"0.744612"
			}
			"trace"
			{
				"cycle"		"0.750766"
			}
			"trace"
			{
				"cycle"		"0.756919"
			}
			"trace"
			{
				"cycle"		"0.763073"
			}
			"trace"
			{
				"cycle"		"0.768201"
			}
			"trace"
			{
				"cycle"		"0.773330"
			}
			"trace"
			{
				"cycle"		"0.778458"
			}
			"trace"
			{
				"cycle"		"0.783586"
			}
			"trace"
			{
				"cycle"		"0.788714"
			}
			"trace"
			{
				"cycle"		"0.793842"
			}
			"trace"
			{
				"cycle"		"0.798970"
			}
			"trace"
			{
				"cycle"		"0.804099"
			}
			"trace"
			{
				"cycle"		"0.809227"
			}
			"trace"
			{
				"cycle"		"0.813329"
			}
			"trace"
			{
				"cycle"		"0.817432"
			}
			"trace"
			{
				"cycle"		"0.821534"
			}
			"trace"
			{
				"cycle"		"0.825637"
			}
			"trace"
			{
				"cycle"		"0.829739"
			}
			"trace"
			{
				"cycle"		"0.833842"
			}
			"trace"
			{
				"cycle"		"0.836919"
			}
			"trace"
			{
				"cycle"		"0.839996"
			}
			"trace"
			{
				"cycle"		"0.843073"
			}
			"trace"
			{
				"cycle"		"0.846150"
			}
			"trace"
			{
				"cycle"		"0.849226"
			}
		}
	}
}
