"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_LEFT_T3 0 0.75"
	}
	"pure"
	{
		"ACT_BB_B_LEFT_T3"
		{
			"trace"
			{
				"cycle"		"0.000000"
			}
			"trace"
			{
				"cycle"		"0.003999"
			}
			"trace"
			{
				"cycle"		"0.008002"
			}
			"trace"
			{
				"cycle"		"0.014000"
			}
			"trace"
			{
				"cycle"		"0.019999"
			}
			"trace"
			{
				"cycle"		"0.024001"
			}
			"trace"
			{
				"cycle"		"0.028000"
			}
			"trace"
			{
				"cycle"		"0.032000"
			}
			"trace"
			{
				"cycle"		"0.035999"
			}
			"trace"
			{
				"cycle"		"0.040001"
			}
			"trace"
			{
				"cycle"		"0.044000"
			}
			"trace"
			{
				"cycle"		"0.047999"
			}
			"trace"
			{
				"cycle"		"0.052002"
			}
			"trace"
			{
				"cycle"		"0.056001"
			}
			"trace"
			{
				"cycle"		"0.060000"
			}
			"trace"
			{
				"cycle"		"0.063999"
			}
			"trace"
			{
				"cycle"		"0.068002"
			}
			"trace"
			{
				"cycle"		"0.072001"
			}
			"trace"
			{
				"cycle"		"0.076000"
			}
			"trace"
			{
				"cycle"		"0.079999"
			}
			"trace"
			{
				"cycle"		"0.088000"
			}
			"trace"
			{
				"cycle"		"0.095999"
			}
			"trace"
			{
				"cycle"		"0.104000"
			}
			"trace"
			{
				"cycle"		"0.114001"
			}
			"trace"
			{
				"cycle"		"0.123999"
			}
			"trace"
			{
				"cycle"		"0.134000"
			}
			"trace"
			{
				"cycle"		"0.148001"
			}
			"trace"
			{
				"cycle"		"0.153999"
			}
			"trace"
			{
				"cycle"		"0.160001"
			}
			"trace"
			{
				"cycle"		"0.166000"
			}
			"trace"
			{
				"cycle"		"0.172002"
			}
			"trace"
			{
				"cycle"		"0.178001"
			}
			"trace"
			{
				"cycle"		"0.183999"
			}
			"trace"
			{
				"cycle"		"0.190001"
			}
			"trace"
			{
				"cycle"		"0.196000"
			}
			"trace"
			{
				"cycle"		"0.202002"
			}
			"trace"
			{
				"cycle"		"0.208001"
			}
			"trace"
			{
				"cycle"		"0.213999"
			}
			"trace"
			{
				"cycle"		"0.220001"
			}
			"trace"
			{
				"cycle"		"0.226000"
			}
			"trace"
			{
				"cycle"		"0.232002"
			}
			"trace"
			{
				"cycle"		"0.238001"
			}
			"trace"
			{
				"cycle"		"0.243999"
			}
			"trace"
			{
				"cycle"		"0.250001"
			}
			"trace"
			{
				"cycle"		"0.256000"
			}
			"trace"
			{
				"cycle"		"0.264001"
			}
			"trace"
			{
				"cycle"		"0.271999"
			}
			"trace"
			{
				"cycle"		"0.280001"
			}
			"trace"
			{
				"cycle"		"0.284000"
			}
			"trace"
			{
				"cycle"		"0.287999"
			}
			"trace"
			{
				"cycle"		"0.292002"
			}
			"trace"
			{
				"cycle"		"0.296001"
			}
			"trace"
			{
				"cycle"		"0.300000"
			}
			"trace"
			{
				"cycle"		"0.303999"
			}
			"trace"
			{
				"cycle"		"0.308001"
			}
			"trace"
			{
				"cycle"		"0.312000"
			}
			"trace"
			{
				"cycle"		"0.315999"
			}
			"trace"
			{
				"cycle"		"0.319998"
			}
			"trace"
			{
				"cycle"		"0.324001"
			}
			"trace"
			{
				"cycle"		"0.328000"
			}
			"trace"
			{
				"cycle"		"0.331999"
			}
			"trace"
			{
				"cycle"		"0.335998"
			}
			"trace"
			{
				"cycle"		"0.340001"
			}
			"trace"
			{
				"cycle"		"0.344000"
			}
			"trace"
			{
				"cycle"		"0.347999"
			}
			"trace"
			{
				"cycle"		"0.352001"
			}
			"trace"
			{
				"cycle"		"0.356000"
			}
			"trace"
			{
				"cycle"		"0.359999"
			}
			"trace"
			{
				"cycle"		"0.368001"
			}
			"trace"
			{
				"cycle"		"0.375999"
			}
			"trace"
			{
				"cycle"		"0.384001"
			}
			"trace"
			{
				"cycle"		"0.391999"
			}
			"trace"
			{
				"cycle"		"0.400000"
			}
			"trace"
			{
				"cycle"		"0.407998"
			}
			"trace"
			{
				"cycle"		"0.416000"
			}
			"trace"
			{
				"cycle"		"0.423998"
			}
			"trace"
			{
				"cycle"		"0.432000"
			}
			"trace"
			{
				"cycle"		"0.437998"
			}
			"trace"
			{
				"cycle"		"0.444000"
			}
			"trace"
			{
				"cycle"		"0.449999"
			}
			"trace"
			{
				"cycle"		"0.455997"
			}
			"trace"
			{
				"cycle"		"0.465998"
			}
			"trace"
			{
				"cycle"		"0.485997"
			}
			"trace"
			{
				"cycle"		"0.511998"
			}
			"trace"
			{
				"cycle"		"0.529997"
			}
			"trace"
			{
				"cycle"		"0.545997"
			}
			"trace"
			{
				"cycle"		"0.557997"
			}
			"trace"
			{
				"cycle"		"0.569998"
			}
			"trace"
			{
				"cycle"		"0.583998"
			}
			"trace"
			{
				"cycle"		"0.608000"
			}
			"trace"
			{
				"cycle"		"0.631997"
			}
			"trace"
			{
				"cycle"		"0.677997"
			}
			"trace"
			{
				"cycle"		"0.741999"
			}
		}
	}
}
