"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_C2_T3 0.2 0.7"
	}
	"pure"
	{
		"ACT_BB_B_C2_T3"
		{
			"trace"
			{
				"cycle"		"0.200000"
			}
			"trace"
			{
				"cycle"		"0.209091"
			}
			"trace"
			{
				"cycle"		"0.214545"
			}
			"trace"
			{
				"cycle"		"0.220000"
			}
			"trace"
			{
				"cycle"		"0.225455"
			}
			"trace"
			{
				"cycle"		"0.230909"
			}
			"trace"
			{
				"cycle"		"0.236364"
			}
			"trace"
			{
				"cycle"		"0.240000"
			}
			"trace"
			{
				"cycle"		"0.243636"
			}
			"trace"
			{
				"cycle"		"0.248182"
			}
			"trace"
			{
				"cycle"		"0.252728"
			}
			"trace"
			{
				"cycle"		"0.257273"
			}
			"trace"
			{
				"cycle"		"0.262727"
			}
			"trace"
			{
				"cycle"		"0.270001"
			}
			"trace"
			{
				"cycle"		"0.277273"
			}
			"trace"
			{
				"cycle"		"0.284546"
			}
			"trace"
			{
				"cycle"		"0.292728"
			}
			"trace"
			{
				"cycle"		"0.301819"
			}
			"trace"
			{
				"cycle"		"0.306364"
			}
			"trace"
			{
				"cycle"		"0.310910"
			}
			"trace"
			{
				"cycle"		"0.315456"
			}
			"trace"
			{
				"cycle"		"0.320001"
			}
			"trace"
			{
				"cycle"		"0.324547"
			}
			"trace"
			{
				"cycle"		"0.328183"
			}
			"trace"
			{
				"cycle"		"0.330001"
			}
			"trace"
			{
				"cycle"		"0.331820"
			}
			"trace"
			{
				"cycle"		"0.333637"
			}
			"trace"
			{
				"cycle"		"0.335456"
			}
			"trace"
			{
				"cycle"		"0.337274"
			}
			"trace"
			{
				"cycle"		"0.339092"
			}
			"trace"
			{
				"cycle"		"0.340910"
			}
			"trace"
			{
				"cycle"		"0.342729"
			}
			"trace"
			{
				"cycle"		"0.344546"
			}
			"trace"
			{
				"cycle"		"0.346365"
			}
			"trace"
			{
				"cycle"		"0.348184"
			}
			"trace"
			{
				"cycle"		"0.350001"
			}
			"trace"
			{
				"cycle"		"0.351820"
			}
			"trace"
			{
				"cycle"		"0.353638"
			}
			"trace"
			{
				"cycle"		"0.355456"
			}
			"trace"
			{
				"cycle"		"0.357274"
			}
			"trace"
			{
				"cycle"		"0.359093"
			}
			"trace"
			{
				"cycle"		"0.360910"
			}
			"trace"
			{
				"cycle"		"0.362729"
			}
			"trace"
			{
				"cycle"		"0.364547"
			}
			"trace"
			{
				"cycle"		"0.366365"
			}
			"trace"
			{
				"cycle"		"0.368183"
			}
			"trace"
			{
				"cycle"		"0.370002"
			}
			"trace"
			{
				"cycle"		"0.371820"
			}
			"trace"
			{
				"cycle"		"0.373638"
			}
			"trace"
			{
				"cycle"		"0.375457"
			}
			"trace"
			{
				"cycle"		"0.377274"
			}
			"trace"
			{
				"cycle"		"0.379093"
			}
			"trace"
			{
				"cycle"		"0.380911"
			}
			"trace"
			{
				"cycle"		"0.382729"
			}
			"trace"
			{
				"cycle"		"0.384547"
			}
			"trace"
			{
				"cycle"		"0.386366"
			}
			"trace"
			{
				"cycle"		"0.388184"
			}
			"trace"
			{
				"cycle"		"0.390002"
			}
			"trace"
			{
				"cycle"		"0.391820"
			}
			"trace"
			{
				"cycle"		"0.394547"
			}
			"trace"
			{
				"cycle"		"0.397275"
			}
			"trace"
			{
				"cycle"		"0.400002"
			}
			"trace"
			{
				"cycle"		"0.402730"
			}
			"trace"
			{
				"cycle"		"0.405456"
			}
			"trace"
			{
				"cycle"		"0.408184"
			}
			"trace"
			{
				"cycle"		"0.411820"
			}
			"trace"
			{
				"cycle"		"0.415457"
			}
			"trace"
			{
				"cycle"		"0.419093"
			}
			"trace"
			{
				"cycle"		"0.422729"
			}
			"trace"
			{
				"cycle"		"0.426366"
			}
			"trace"
			{
				"cycle"		"0.430003"
			}
			"trace"
			{
				"cycle"		"0.433639"
			}
			"trace"
			{
				"cycle"		"0.437276"
			}
			"trace"
			{
				"cycle"		"0.440912"
			}
			"trace"
			{
				"cycle"		"0.443640"
			}
			"trace"
			{
				"cycle"		"0.446366"
			}
			"trace"
			{
				"cycle"		"0.449094"
			}
			"trace"
			{
				"cycle"		"0.451821"
			}
			"trace"
			{
				"cycle"		"0.454549"
			}
			"trace"
			{
				"cycle"		"0.464549"
			}
			"trace"
			{
				"cycle"		"0.472730"
			}
			"trace"
			{
				"cycle"		"0.478185"
			}
			"trace"
			{
				"cycle"		"0.484549"
			}
			"trace"
			{
				"cycle"		"0.491822"
			}
			"trace"
			{
				"cycle"		"0.499095"
			}
			"trace"
			{
				"cycle"		"0.503640"
			}
			"trace"
			{
				"cycle"		"0.507276"
			}
			"trace"
			{
				"cycle"		"0.510912"
			}
			"trace"
			{
				"cycle"		"0.514548"
			}
			"trace"
			{
				"cycle"		"0.519094"
			}
			"trace"
			{
				"cycle"		"0.523640"
			}
			"trace"
			{
				"cycle"		"0.528185"
			}
			"trace"
			{
				"cycle"		"0.533639"
			}
			"trace"
			{
				"cycle"		"0.539094"
			}
			"trace"
			{
				"cycle"		"0.543639"
			}
			"trace"
			{
				"cycle"		"0.548184"
			}
			"trace"
			{
				"cycle"		"0.552730"
			}
			"trace"
			{
				"cycle"		"0.557275"
			}
			"trace"
			{
				"cycle"		"0.561820"
			}
			"trace"
			{
				"cycle"		"0.566366"
			}
			"trace"
			{
				"cycle"		"0.570911"
			}
			"trace"
			{
				"cycle"		"0.575457"
			}
			"trace"
			{
				"cycle"		"0.580911"
			}
			"trace"
			{
				"cycle"		"0.586365"
			}
			"trace"
			{
				"cycle"		"0.591820"
			}
			"trace"
			{
				"cycle"		"0.596365"
			}
			"trace"
			{
				"cycle"		"0.600911"
			}
			"trace"
			{
				"cycle"		"0.605456"
			}
			"trace"
			{
				"cycle"		"0.610001"
			}
			"trace"
			{
				"cycle"		"0.614547"
			}
			"trace"
			{
				"cycle"		"0.619092"
			}
			"trace"
			{
				"cycle"		"0.623637"
			}
			"trace"
			{
				"cycle"		"0.628183"
			}
			"trace"
			{
				"cycle"		"0.632728"
			}
			"trace"
			{
				"cycle"		"0.637273"
			}
			"trace"
			{
				"cycle"		"0.640910"
			}
			"trace"
			{
				"cycle"		"0.644546"
			}
			"trace"
			{
				"cycle"		"0.648183"
			}
			"trace"
			{
				"cycle"		"0.651819"
			}
			"trace"
			{
				"cycle"		"0.655456"
			}
			"trace"
			{
				"cycle"		"0.659092"
			}
			"trace"
			{
				"cycle"		"0.662728"
			}
			"trace"
			{
				"cycle"		"0.666364"
			}
			"trace"
			{
				"cycle"		"0.670000"
			}
			"trace"
			{
				"cycle"		"0.673637"
			}
			"trace"
			{
				"cycle"		"0.677273"
			}
			"trace"
			{
				"cycle"		"0.680909"
			}
			"trace"
			{
				"cycle"		"0.686364"
			}
			"trace"
			{
				"cycle"		"0.692728"
			}
			"trace"
			{
				"cycle"		"0.699090"
			}
		}
	}
}
