"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_C3_T2 0.1 0.7"
	}
	"pure"
	{
		"ACT_BB_B_C3_T2"
		{
			"trace"
			{
				"cycle"		"0.100833"
			}
			"trace"
			{
				"cycle"		"0.110000"
			}
			"trace"
			{
				"cycle"		"0.116417"
			}
			"trace"
			{
				"cycle"		"0.122833"
			}
			"trace"
			{
				"cycle"		"0.129250"
			}
			"trace"
			{
				"cycle"		"0.135667"
			}
			"trace"
			{
				"cycle"		"0.142083"
			}
			"trace"
			{
				"cycle"		"0.149417"
			}
			"trace"
			{
				"cycle"		"0.156750"
			}
			"trace"
			{
				"cycle"		"0.164084"
			}
			"trace"
			{
				"cycle"		"0.171417"
			}
			"trace"
			{
				"cycle"		"0.178750"
			}
			"trace"
			{
				"cycle"		"0.186084"
			}
			"trace"
			{
				"cycle"		"0.192500"
			}
			"trace"
			{
				"cycle"		"0.198001"
			}
			"trace"
			{
				"cycle"		"0.202584"
			}
			"trace"
			{
				"cycle"		"0.206251"
			}
			"trace"
			{
				"cycle"		"0.209917"
			}
			"trace"
			{
				"cycle"		"0.213584"
			}
			"trace"
			{
				"cycle"		"0.217251"
			}
			"trace"
			{
				"cycle"		"0.220917"
			}
			"trace"
			{
				"cycle"		"0.224584"
			}
			"trace"
			{
				"cycle"		"0.228251"
			}
			"trace"
			{
				"cycle"		"0.231917"
			}
			"trace"
			{
				"cycle"		"0.235584"
			}
			"trace"
			{
				"cycle"		"0.239251"
			}
			"trace"
			{
				"cycle"		"0.242917"
			}
			"trace"
			{
				"cycle"		"0.246584"
			}
			"trace"
			{
				"cycle"		"0.250251"
			}
			"trace"
			{
				"cycle"		"0.256668"
			}
			"trace"
			{
				"cycle"		"0.263084"
			}
			"trace"
			{
				"cycle"		"0.269501"
			}
			"trace"
			{
				"cycle"		"0.276834"
			}
			"trace"
			{
				"cycle"		"0.285084"
			}
			"trace"
			{
				"cycle"		"0.295168"
			}
			"trace"
			{
				"cycle"		"0.308918"
			}
			"trace"
			{
				"cycle"		"0.322668"
			}
			"trace"
			{
				"cycle"		"0.333668"
			}
			"trace"
			{
				"cycle"		"0.342835"
			}
			"trace"
			{
				"cycle"		"0.352001"
			}
			"trace"
			{
				"cycle"		"0.361168"
			}
			"trace"
			{
				"cycle"		"0.368502"
			}
			"trace"
			{
				"cycle"		"0.374918"
			}
			"trace"
			{
				"cycle"		"0.381335"
			}
			"trace"
			{
				"cycle"		"0.387752"
			}
			"trace"
			{
				"cycle"		"0.394168"
			}
			"trace"
			{
				"cycle"		"0.401502"
			}
			"trace"
			{
				"cycle"		"0.412502"
			}
			"trace"
			{
				"cycle"		"0.429002"
			}
			"trace"
			{
				"cycle"		"0.436335"
			}
			"trace"
			{
				"cycle"		"0.443669"
			}
			"trace"
			{
				"cycle"		"0.450085"
			}
			"trace"
			{
				"cycle"		"0.454669"
			}
			"trace"
			{
				"cycle"		"0.458336"
			}
			"trace"
			{
				"cycle"		"0.461086"
			}
			"trace"
			{
				"cycle"		"0.463836"
			}
			"trace"
			{
				"cycle"		"0.466586"
			}
			"trace"
			{
				"cycle"		"0.469336"
			}
			"trace"
			{
				"cycle"		"0.472086"
			}
			"trace"
			{
				"cycle"		"0.475752"
			}
			"trace"
			{
				"cycle"		"0.478502"
			}
			"trace"
			{
				"cycle"		"0.482169"
			}
			"trace"
			{
				"cycle"		"0.485836"
			}
			"trace"
			{
				"cycle"		"0.489502"
			}
			"trace"
			{
				"cycle"		"0.492252"
			}
			"trace"
			{
				"cycle"		"0.495003"
			}
			"trace"
			{
				"cycle"		"0.497753"
			}
			"trace"
			{
				"cycle"		"0.500503"
			}
			"trace"
			{
				"cycle"		"0.502336"
			}
			"trace"
			{
				"cycle"		"0.504169"
			}
			"trace"
			{
				"cycle"		"0.506002"
			}
			"trace"
			{
				"cycle"		"0.507836"
			}
			"trace"
			{
				"cycle"		"0.509669"
			}
			"trace"
			{
				"cycle"		"0.511503"
			}
			"trace"
			{
				"cycle"		"0.513336"
			}
			"trace"
			{
				"cycle"		"0.515169"
			}
			"trace"
			{
				"cycle"		"0.517003"
			}
			"trace"
			{
				"cycle"		"0.518836"
			}
			"trace"
			{
				"cycle"		"0.520669"
			}
			"trace"
			{
				"cycle"		"0.522503"
			}
			"trace"
			{
				"cycle"		"0.524336"
			}
			"trace"
			{
				"cycle"		"0.526169"
			}
			"trace"
			{
				"cycle"		"0.528003"
			}
			"trace"
			{
				"cycle"		"0.529836"
			}
			"trace"
			{
				"cycle"		"0.532586"
			}
			"trace"
			{
				"cycle"		"0.535336"
			}
			"trace"
			{
				"cycle"		"0.538086"
			}
			"trace"
			{
				"cycle"		"0.540836"
			}
			"trace"
			{
				"cycle"		"0.545419"
			}
			"trace"
			{
				"cycle"		"0.550003"
			}
			"trace"
			{
				"cycle"		"0.562836"
			}
			"trace"
			{
				"cycle"		"0.592170"
			}
			"trace"
			{
				"cycle"		"0.655420"
			}
			"trace"
			{
				"cycle"		"0.673754"
			}
			"trace"
			{
				"cycle"		"0.685670"
			}
			"trace"
			{
				"cycle"		"0.694837"
			}
		}
	}
}
