"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_A_C1_T1 0.4 0.6"
	}
	"pure"
	{
		"ACT_BB_A_C1_T1"
		{
			"trace"
			{
				"cycle"		"0.400001"
			}
			"trace"
			{
				"cycle"		"0.420834"
			}
			"trace"
			{
				"cycle"		"0.441668"
			}
			"trace"
			{
				"cycle"		"0.470834"
			}
			"trace"
			{
				"cycle"		"0.558333"
			}
			"trace"
			{
				"cycle"		"0.589583"
			}
		}
	}
}
