"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_C3_T3 0.4 0.8"
	}
	"pure"
	{
		"ACT_BB_B_C3_T3"
		{
			"trace"
			{
				"cycle"		"0.400279"
			}
			"trace"
			{
				"cycle"		"0.405626"
			}
			"trace"
			{
				"cycle"		"0.407917"
			}
			"trace"
			{
				"cycle"		"0.414793"
			}
			"trace"
			{
				"cycle"		"0.416320"
			}
			"trace"
			{
				"cycle"		"0.423196"
			}
			"trace"
			{
				"cycle"		"0.424723"
			}
			"trace"
			{
				"cycle"		"0.428543"
			}
			"trace"
			{
				"cycle"		"0.432362"
			}
			"trace"
			{
				"cycle"		"0.439237"
			}
			"trace"
			{
				"cycle"		"0.447640"
			}
			"trace"
			{
				"cycle"		"0.458335"
			}
			"trace"
			{
				"cycle"		"0.468265"
			}
			"trace"
			{
				"cycle"		"0.478196"
			}
			"trace"
			{
				"cycle"		"0.487363"
			}
			"trace"
			{
				"cycle"		"0.494238"
			}
			"trace"
			{
				"cycle"		"0.501113"
			}
			"trace"
			{
				"cycle"		"0.508753"
			}
			"trace"
			{
				"cycle"		"0.515627"
			}
			"trace"
			{
				"cycle"		"0.523267"
			}
			"trace"
			{
				"cycle"		"0.529378"
			}
			"trace"
			{
				"cycle"		"0.533961"
			}
			"trace"
			{
				"cycle"		"0.540072"
			}
			"trace"
			{
				"cycle"		"0.546948"
			}
			"trace"
			{
				"cycle"		"0.553059"
			}
			"trace"
			{
				"cycle"		"0.560698"
			}
			"trace"
			{
				"cycle"		"0.568337"
			}
			"trace"
			{
				"cycle"		"0.571392"
			}
			"trace"
			{
				"cycle"		"0.575212"
			}
			"trace"
			{
				"cycle"		"0.578268"
			}
			"trace"
			{
				"cycle"		"0.582087"
			}
			"trace"
			{
				"cycle"		"0.585143"
			}
			"trace"
			{
				"cycle"		"0.588198"
			}
			"trace"
			{
				"cycle"		"0.592018"
			}
			"trace"
			{
				"cycle"		"0.603477"
			}
			"trace"
			{
				"cycle"		"0.606532"
			}
			"trace"
			{
				"cycle"		"0.609588"
			}
			"trace"
			{
				"cycle"		"0.612643"
			}
			"trace"
			{
				"cycle"		"0.615699"
			}
			"trace"
			{
				"cycle"		"0.618755"
			}
			"trace"
			{
				"cycle"		"0.621810"
			}
			"trace"
			{
				"cycle"		"0.624866"
			}
			"trace"
			{
				"cycle"		"0.627158"
			}
			"trace"
			{
				"cycle"		"0.629449"
			}
			"trace"
			{
				"cycle"		"0.631741"
			}
			"trace"
			{
				"cycle"		"0.634032"
			}
			"trace"
			{
				"cycle"		"0.635561"
			}
			"trace"
			{
				"cycle"		"0.637088"
			}
			"trace"
			{
				"cycle"		"0.638616"
			}
			"trace"
			{
				"cycle"		"0.640144"
			}
			"trace"
			{
				"cycle"		"0.641672"
			}
			"trace"
			{
				"cycle"		"0.643199"
			}
			"trace"
			{
				"cycle"		"0.644727"
			}
			"trace"
			{
				"cycle"		"0.646255"
			}
			"trace"
			{
				"cycle"		"0.647783"
			}
			"trace"
			{
				"cycle"		"0.649311"
			}
			"trace"
			{
				"cycle"		"0.650838"
			}
			"trace"
			{
				"cycle"		"0.652367"
			}
			"trace"
			{
				"cycle"		"0.653894"
			}
			"trace"
			{
				"cycle"		"0.655422"
			}
			"trace"
			{
				"cycle"		"0.656950"
			}
			"trace"
			{
				"cycle"		"0.658478"
			}
			"trace"
			{
				"cycle"		"0.660005"
			}
			"trace"
			{
				"cycle"		"0.661533"
			}
			"trace"
			{
				"cycle"		"0.663061"
			}
			"trace"
			{
				"cycle"		"0.664589"
			}
			"trace"
			{
				"cycle"		"0.666116"
			}
			"trace"
			{
				"cycle"		"0.667644"
			}
			"trace"
			{
				"cycle"		"0.669173"
			}
			"trace"
			{
				"cycle"		"0.670700"
			}
			"trace"
			{
				"cycle"		"0.672228"
			}
			"trace"
			{
				"cycle"		"0.673756"
			}
			"trace"
			{
				"cycle"		"0.675284"
			}
			"trace"
			{
				"cycle"		"0.677575"
			}
			"trace"
			{
				"cycle"		"0.679867"
			}
			"trace"
			{
				"cycle"		"0.682159"
			}
			"trace"
			{
				"cycle"		"0.684450"
			}
			"trace"
			{
				"cycle"		"0.685978"
			}
			"trace"
			{
				"cycle"		"0.687506"
			}
			"trace"
			{
				"cycle"		"0.689033"
			}
			"trace"
			{
				"cycle"		"0.690562"
			}
			"trace"
			{
				"cycle"		"0.692090"
			}
			"trace"
			{
				"cycle"		"0.694381"
			}
			"trace"
			{
				"cycle"		"0.696673"
			}
			"trace"
			{
				"cycle"		"0.698201"
			}
			"trace"
			{
				"cycle"		"0.699728"
			}
			"trace"
			{
				"cycle"		"0.702020"
			}
			"trace"
			{
				"cycle"		"0.704312"
			}
			"trace"
			{
				"cycle"		"0.706604"
			}
			"trace"
			{
				"cycle"		"0.708895"
			}
			"trace"
			{
				"cycle"		"0.711951"
			}
			"trace"
			{
				"cycle"		"0.715007"
			}
			"trace"
			{
				"cycle"		"0.718062"
			}
			"trace"
			{
				"cycle"		"0.721882"
			}
			"trace"
			{
				"cycle"		"0.725701"
			}
			"trace"
			{
				"cycle"		"0.729521"
			}
			"trace"
			{
				"cycle"		"0.733340"
			}
			"trace"
			{
				"cycle"		"0.737160"
			}
			"trace"
			{
				"cycle"		"0.740980"
			}
			"trace"
			{
				"cycle"		"0.744799"
			}
			"trace"
			{
				"cycle"		"0.748618"
			}
			"trace"
			{
				"cycle"		"0.753202"
			}
			"trace"
			{
				"cycle"		"0.758549"
			}
			"trace"
			{
				"cycle"		"0.763897"
			}
			"trace"
			{
				"cycle"		"0.771535"
			}
			"trace"
			{
				"cycle"		"0.781466"
			}
		}
	}
}
