"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_C3_T1 0.15 0.59"
	}
	"pure"
	{
		"ACT_BB_B_C3_T1"
		{
			"trace"
			{
				"cycle"		"0.150500"
			}
			"trace"
			{
				"cycle"		"0.158667"
			}
			"trace"
			{
				"cycle"		"0.166833"
			}
			"trace"
			{
				"cycle"		"0.173833"
			}
			"trace"
			{
				"cycle"		"0.180834"
			}
			"trace"
			{
				"cycle"		"0.186667"
			}
			"trace"
			{
				"cycle"		"0.192500"
			}
			"trace"
			{
				"cycle"		"0.197167"
			}
			"trace"
			{
				"cycle"		"0.201833"
			}
			"trace"
			{
				"cycle"		"0.206500"
			}
			"trace"
			{
				"cycle"		"0.211167"
			}
			"trace"
			{
				"cycle"		"0.214667"
			}
			"trace"
			{
				"cycle"		"0.218167"
			}
			"trace"
			{
				"cycle"		"0.221667"
			}
			"trace"
			{
				"cycle"		"0.225167"
			}
			"trace"
			{
				"cycle"		"0.228667"
			}
			"trace"
			{
				"cycle"		"0.232167"
			}
			"trace"
			{
				"cycle"		"0.235667"
			}
			"trace"
			{
				"cycle"		"0.239167"
			}
			"trace"
			{
				"cycle"		"0.242667"
			}
			"trace"
			{
				"cycle"		"0.246167"
			}
			"trace"
			{
				"cycle"		"0.249667"
			}
			"trace"
			{
				"cycle"		"0.257833"
			}
			"trace"
			{
				"cycle"		"0.266000"
			}
			"trace"
			{
				"cycle"		"0.274166"
			}
			"trace"
			{
				"cycle"		"0.282333"
			}
			"trace"
			{
				"cycle"		"0.289333"
			}
			"trace"
			{
				"cycle"		"0.296333"
			}
			"trace"
			{
				"cycle"		"0.311499"
			}
			"trace"
			{
				"cycle"		"0.324333"
			}
			"trace"
			{
				"cycle"		"0.338333"
			}
			"trace"
			{
				"cycle"		"0.352333"
			}
			"trace"
			{
				"cycle"		"0.359333"
			}
			"trace"
			{
				"cycle"		"0.367499"
			}
			"trace"
			{
				"cycle"		"0.375666"
			}
			"trace"
			{
				"cycle"		"0.383833"
			}
			"trace"
			{
				"cycle"		"0.391999"
			}
			"trace"
			{
				"cycle"		"0.400166"
			}
			"trace"
			{
				"cycle"		"0.410666"
			}
			"trace"
			{
				"cycle"		"0.421166"
			}
			"trace"
			{
				"cycle"		"0.432832"
			}
			"trace"
			{
				"cycle"		"0.437499"
			}
			"trace"
			{
				"cycle"		"0.443332"
			}
			"trace"
			{
				"cycle"		"0.449165"
			}
			"trace"
			{
				"cycle"		"0.454999"
			}
			"trace"
			{
				"cycle"		"0.459665"
			}
			"trace"
			{
				"cycle"		"0.463166"
			}
			"trace"
			{
				"cycle"		"0.466665"
			}
			"trace"
			{
				"cycle"		"0.470165"
			}
			"trace"
			{
				"cycle"		"0.473666"
			}
			"trace"
			{
				"cycle"		"0.475999"
			}
			"trace"
			{
				"cycle"		"0.478332"
			}
			"trace"
			{
				"cycle"		"0.481832"
			}
			"trace"
			{
				"cycle"		"0.485332"
			}
			"trace"
			{
				"cycle"		"0.488832"
			}
			"trace"
			{
				"cycle"		"0.492332"
			}
			"trace"
			{
				"cycle"		"0.495832"
			}
			"trace"
			{
				"cycle"		"0.498165"
			}
			"trace"
			{
				"cycle"		"0.500499"
			}
			"trace"
			{
				"cycle"		"0.502832"
			}
			"trace"
			{
				"cycle"		"0.505165"
			}
			"trace"
			{
				"cycle"		"0.507499"
			}
			"trace"
			{
				"cycle"		"0.509832"
			}
			"trace"
			{
				"cycle"		"0.512165"
			}
			"trace"
			{
				"cycle"		"0.514499"
			}
			"trace"
			{
				"cycle"		"0.516832"
			}
			"trace"
			{
				"cycle"		"0.519165"
			}
			"trace"
			{
				"cycle"		"0.521499"
			}
			"trace"
			{
				"cycle"		"0.523833"
			}
			"trace"
			{
				"cycle"		"0.526166"
			}
			"trace"
			{
				"cycle"		"0.528499"
			}
			"trace"
			{
				"cycle"		"0.530833"
			}
			"trace"
			{
				"cycle"		"0.533166"
			}
			"trace"
			{
				"cycle"		"0.535499"
			}
			"trace"
			{
				"cycle"		"0.537833"
			}
			"trace"
			{
				"cycle"		"0.540166"
			}
			"trace"
			{
				"cycle"		"0.542499"
			}
			"trace"
			{
				"cycle"		"0.544833"
			}
			"trace"
			{
				"cycle"		"0.547166"
			}
			"trace"
			{
				"cycle"		"0.549499"
			}
			"trace"
			{
				"cycle"		"0.584500"
			}
		}
	}
}
