"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_R_C2_T2 0.45 0.6"
	}
	"pure"
	{
		"ACT_BB_R_C2_T2"
		{
			"trace"
			{
				"cycle"		"0.450772"
			}
			"trace"
			{
				"cycle"		"0.463079"
			}
			"trace"
			{
				"cycle"		"0.473849"
			}
			"trace"
			{
				"cycle"		"0.486156"
			}
			"trace"
			{
				"cycle"		"0.501540"
			}
			"trace"
			{
				"cycle"		"0.524617"
			}
			"trace"
			{
				"cycle"		"0.563079"
			}
		}
	}
}
