"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_C3_T3 0.2 0.8"
	}
	"pure"
	{
		"ACT_BB_B_C3_T3"
		{
			"trace"
			{
				"cycle"		"0.200833"
			}
			"trace"
			{
				"cycle"		"0.202500"
			}
			"trace"
			{
				"cycle"		"0.203333"
			}
			"trace"
			{
				"cycle"		"0.204166"
			}
			"trace"
			{
				"cycle"		"0.204999"
			}
			"trace"
			{
				"cycle"		"0.205833"
			}
			"trace"
			{
				"cycle"		"0.207499"
			}
			"trace"
			{
				"cycle"		"0.209166"
			}
			"trace"
			{
				"cycle"		"0.209999"
			}
			"trace"
			{
				"cycle"		"0.210833"
			}
			"trace"
			{
				"cycle"		"0.211666"
			}
			"trace"
			{
				"cycle"		"0.212500"
			}
			"trace"
			{
				"cycle"		"0.213333"
			}
			"trace"
			{
				"cycle"		"0.214166"
			}
			"trace"
			{
				"cycle"		"0.214999"
			}
			"trace"
			{
				"cycle"		"0.215833"
			}
			"trace"
			{
				"cycle"		"0.216666"
			}
			"trace"
			{
				"cycle"		"0.218333"
			}
			"trace"
			{
				"cycle"		"0.219999"
			}
			"trace"
			{
				"cycle"		"0.221666"
			}
			"trace"
			{
				"cycle"		"0.223333"
			}
			"trace"
			{
				"cycle"		"0.225000"
			}
			"trace"
			{
				"cycle"		"0.226666"
			}
			"trace"
			{
				"cycle"		"0.228333"
			}
			"trace"
			{
				"cycle"		"0.229999"
			}
			"trace"
			{
				"cycle"		"0.231666"
			}
			"trace"
			{
				"cycle"		"0.233333"
			}
			"trace"
			{
				"cycle"		"0.235833"
			}
			"trace"
			{
				"cycle"		"0.238333"
			}
			"trace"
			{
				"cycle"		"0.240833"
			}
			"trace"
			{
				"cycle"		"0.244999"
			}
			"trace"
			{
				"cycle"		"0.249999"
			}
			"trace"
			{
				"cycle"		"0.259166"
			}
			"trace"
			{
				"cycle"		"0.267500"
			}
			"trace"
			{
				"cycle"		"0.277500"
			}
			"trace"
			{
				"cycle"		"0.284166"
			}
			"trace"
			{
				"cycle"		"0.289167"
			}
			"trace"
			{
				"cycle"		"0.303333"
			}
			"trace"
			{
				"cycle"		"0.312500"
			}
			"trace"
			{
				"cycle"		"0.319167"
			}
			"trace"
			{
				"cycle"		"0.327500"
			}
			"trace"
			{
				"cycle"		"0.335000"
			}
			"trace"
			{
				"cycle"		"0.340000"
			}
			"trace"
			{
				"cycle"		"0.345834"
			}
			"trace"
			{
				"cycle"		"0.351667"
			}
			"trace"
			{
				"cycle"		"0.355000"
			}
			"trace"
			{
				"cycle"		"0.358334"
			}
			"trace"
			{
				"cycle"		"0.361667"
			}
			"trace"
			{
				"cycle"		"0.365000"
			}
			"trace"
			{
				"cycle"		"0.370001"
			}
			"trace"
			{
				"cycle"		"0.376667"
			}
			"trace"
			{
				"cycle"		"0.380000"
			}
			"trace"
			{
				"cycle"		"0.383334"
			}
			"trace"
			{
				"cycle"		"0.385834"
			}
			"trace"
			{
				"cycle"		"0.388334"
			}
			"trace"
			{
				"cycle"		"0.390834"
			}
			"trace"
			{
				"cycle"		"0.392500"
			}
			"trace"
			{
				"cycle"		"0.394167"
			}
			"trace"
			{
				"cycle"		"0.395834"
			}
			"trace"
			{
				"cycle"		"0.397500"
			}
			"trace"
			{
				"cycle"		"0.399167"
			}
			"trace"
			{
				"cycle"		"0.404167"
			}
			"trace"
			{
				"cycle"		"0.406667"
			}
			"trace"
			{
				"cycle"		"0.408334"
			}
			"trace"
			{
				"cycle"		"0.415000"
			}
			"trace"
			{
				"cycle"		"0.416667"
			}
			"trace"
			{
				"cycle"		"0.423334"
			}
			"trace"
			{
				"cycle"		"0.425000"
			}
			"trace"
			{
				"cycle"		"0.429167"
			}
			"trace"
			{
				"cycle"		"0.432500"
			}
			"trace"
			{
				"cycle"		"0.439167"
			}
			"trace"
			{
				"cycle"		"0.447500"
			}
			"trace"
			{
				"cycle"		"0.458333"
			}
			"trace"
			{
				"cycle"		"0.468334"
			}
			"trace"
			{
				"cycle"		"0.478333"
			}
			"trace"
			{
				"cycle"		"0.487500"
			}
			"trace"
			{
				"cycle"		"0.494167"
			}
			"trace"
			{
				"cycle"		"0.500833"
			}
			"trace"
			{
				"cycle"		"0.508333"
			}
			"trace"
			{
				"cycle"		"0.514167"
			}
			"trace"
			{
				"cycle"		"0.522500"
			}
			"trace"
			{
				"cycle"		"0.529167"
			}
			"trace"
			{
				"cycle"		"0.534167"
			}
			"trace"
			{
				"cycle"		"0.540834"
			}
			"trace"
			{
				"cycle"		"0.547501"
			}
			"trace"
			{
				"cycle"		"0.554168"
			}
			"trace"
			{
				"cycle"		"0.561667"
			}
			"trace"
			{
				"cycle"		"0.569168"
			}
			"trace"
			{
				"cycle"		"0.572501"
			}
			"trace"
			{
				"cycle"		"0.576668"
			}
			"trace"
			{
				"cycle"		"0.580001"
			}
			"trace"
			{
				"cycle"		"0.584168"
			}
			"trace"
			{
				"cycle"		"0.587501"
			}
			"trace"
			{
				"cycle"		"0.591668"
			}
			"trace"
			{
				"cycle"		"0.603335"
			}
			"trace"
			{
				"cycle"		"0.606668"
			}
			"trace"
			{
				"cycle"		"0.610001"
			}
			"trace"
			{
				"cycle"		"0.613335"
			}
			"trace"
			{
				"cycle"		"0.616668"
			}
			"trace"
			{
				"cycle"		"0.619168"
			}
			"trace"
			{
				"cycle"		"0.622502"
			}
			"trace"
			{
				"cycle"		"0.625835"
			}
			"trace"
			{
				"cycle"		"0.628335"
			}
			"trace"
			{
				"cycle"		"0.630835"
			}
			"trace"
			{
				"cycle"		"0.633335"
			}
			"trace"
			{
				"cycle"		"0.635002"
			}
			"trace"
			{
				"cycle"		"0.636668"
			}
			"trace"
			{
				"cycle"		"0.638335"
			}
			"trace"
			{
				"cycle"		"0.640002"
			}
			"trace"
			{
				"cycle"		"0.641669"
			}
			"trace"
			{
				"cycle"		"0.643335"
			}
			"trace"
			{
				"cycle"		"0.645002"
			}
			"trace"
			{
				"cycle"		"0.646669"
			}
			"trace"
			{
				"cycle"		"0.647502"
			}
			"trace"
			{
				"cycle"		"0.649169"
			}
			"trace"
			{
				"cycle"		"0.650835"
			}
			"trace"
			{
				"cycle"		"0.652502"
			}
			"trace"
			{
				"cycle"		"0.654169"
			}
			"trace"
			{
				"cycle"		"0.655836"
			}
			"trace"
			{
				"cycle"		"0.657502"
			}
			"trace"
			{
				"cycle"		"0.659169"
			}
			"trace"
			{
				"cycle"		"0.660836"
			}
			"trace"
			{
				"cycle"		"0.662502"
			}
			"trace"
			{
				"cycle"		"0.664169"
			}
			"trace"
			{
				"cycle"		"0.665836"
			}
			"trace"
			{
				"cycle"		"0.667502"
			}
			"trace"
			{
				"cycle"		"0.669169"
			}
			"trace"
			{
				"cycle"		"0.670836"
			}
			"trace"
			{
				"cycle"		"0.672502"
			}
			"trace"
			{
				"cycle"		"0.674169"
			}
			"trace"
			{
				"cycle"		"0.675836"
			}
			"trace"
			{
				"cycle"		"0.677502"
			}
			"trace"
			{
				"cycle"		"0.679169"
			}
			"trace"
			{
				"cycle"		"0.680836"
			}
			"trace"
			{
				"cycle"		"0.682503"
			}
			"trace"
			{
				"cycle"		"0.685002"
			}
			"trace"
			{
				"cycle"		"0.686669"
			}
			"trace"
			{
				"cycle"		"0.688336"
			}
			"trace"
			{
				"cycle"		"0.690002"
			}
			"trace"
			{
				"cycle"		"0.691669"
			}
			"trace"
			{
				"cycle"		"0.694169"
			}
			"trace"
			{
				"cycle"		"0.695836"
			}
			"trace"
			{
				"cycle"		"0.697503"
			}
			"trace"
			{
				"cycle"		"0.699169"
			}
			"trace"
			{
				"cycle"		"0.701669"
			}
			"trace"
			{
				"cycle"		"0.704170"
			}
			"trace"
			{
				"cycle"		"0.706669"
			}
			"trace"
			{
				"cycle"		"0.709170"
			}
			"trace"
			{
				"cycle"		"0.711669"
			}
			"trace"
			{
				"cycle"		"0.714170"
			}
			"trace"
			{
				"cycle"		"0.716670"
			}
			"trace"
			{
				"cycle"		"0.720003"
			}
			"trace"
			{
				"cycle"		"0.723336"
			}
			"trace"
			{
				"cycle"		"0.726670"
			}
			"trace"
			{
				"cycle"		"0.730837"
			}
			"trace"
			{
				"cycle"		"0.735003"
			}
			"trace"
			{
				"cycle"		"0.739170"
			}
			"trace"
			{
				"cycle"		"0.743337"
			}
			"trace"
			{
				"cycle"		"0.747503"
			}
			"trace"
			{
				"cycle"		"0.751670"
			}
			"trace"
			{
				"cycle"		"0.756670"
			}
			"trace"
			{
				"cycle"		"0.762504"
			}
			"trace"
			{
				"cycle"		"0.769170"
			}
			"trace"
			{
				"cycle"		"0.778337"
			}
		}
	}
}
