"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_C1_T3 0 1"
	}
	"pure"
	{
		"ACT_BB_B_C1_T3"
		{
			"trace"
			{
				"cycle"		"0.000000"
			}
			"trace"
			{
				"cycle"		"0.022857"
			}
			"trace"
			{
				"cycle"		"0.045714"
			}
			"trace"
			{
				"cycle"		"0.067142"
			}
			"trace"
			{
				"cycle"		"0.088571"
			}
			"trace"
			{
				"cycle"		"0.102857"
			}
			"trace"
			{
				"cycle"		"0.107143"
			}
			"trace"
			{
				"cycle"		"0.111429"
			}
			"trace"
			{
				"cycle"		"0.115714"
			}
			"trace"
			{
				"cycle"		"0.121429"
			}
			"trace"
			{
				"cycle"		"0.127143"
			}
			"trace"
			{
				"cycle"		"0.134286"
			}
			"trace"
			{
				"cycle"		"0.142858"
			}
			"trace"
			{
				"cycle"		"0.155714"
			}
			"trace"
			{
				"cycle"		"0.161428"
			}
			"trace"
			{
				"cycle"		"0.165714"
			}
			"trace"
			{
				"cycle"		"0.170000"
			}
			"trace"
			{
				"cycle"		"0.174285"
			}
			"trace"
			{
				"cycle"		"0.178571"
			}
			"trace"
			{
				"cycle"		"0.182857"
			}
			"trace"
			{
				"cycle"		"0.187143"
			}
			"trace"
			{
				"cycle"		"0.191429"
			}
			"trace"
			{
				"cycle"		"0.195713"
			}
			"trace"
			{
				"cycle"		"0.199999"
			}
			"trace"
			{
				"cycle"		"0.205714"
			}
			"trace"
			{
				"cycle"		"0.211428"
			}
			"trace"
			{
				"cycle"		"0.217142"
			}
			"trace"
			{
				"cycle"		"0.221428"
			}
			"trace"
			{
				"cycle"		"0.225714"
			}
			"trace"
			{
				"cycle"		"0.230000"
			}
			"trace"
			{
				"cycle"		"0.234286"
			}
			"trace"
			{
				"cycle"		"0.238570"
			}
			"trace"
			{
				"cycle"		"0.242856"
			}
			"trace"
			{
				"cycle"		"0.259999"
			}
			"trace"
			{
				"cycle"		"0.291428"
			}
			"trace"
			{
				"cycle"		"0.352857"
			}
			"trace"
			{
				"cycle"		"0.377142"
			}
			"trace"
			{
				"cycle"		"0.398570"
			}
			"trace"
			{
				"cycle"		"0.424284"
			}
			"trace"
			{
				"cycle"		"0.462855"
			}
			"trace"
			{
				"cycle"		"0.475713"
			}
			"trace"
			{
				"cycle"		"0.479998"
			}
			"trace"
			{
				"cycle"		"0.484284"
			}
			"trace"
			{
				"cycle"		"0.487142"
			}
			"trace"
			{
				"cycle"		"0.489998"
			}
			"trace"
			{
				"cycle"		"0.492856"
			}
			"trace"
			{
				"cycle"		"0.495712"
			}
			"trace"
			{
				"cycle"		"0.498570"
			}
			"trace"
			{
				"cycle"		"0.501427"
			}
			"trace"
			{
				"cycle"		"0.504284"
			}
			"trace"
			{
				"cycle"		"0.507142"
			}
			"trace"
			{
				"cycle"		"0.509999"
			}
			"trace"
			{
				"cycle"		"0.512856"
			}
			"trace"
			{
				"cycle"		"0.515713"
			}
			"trace"
			{
				"cycle"		"0.517141"
			}
			"trace"
			{
				"cycle"		"0.518571"
			}
			"trace"
			{
				"cycle"		"0.519999"
			}
			"trace"
			{
				"cycle"		"0.521427"
			}
			"trace"
			{
				"cycle"		"0.522855"
			}
			"trace"
			{
				"cycle"		"0.524285"
			}
			"trace"
			{
				"cycle"		"0.525713"
			}
			"trace"
			{
				"cycle"		"0.527142"
			}
			"trace"
			{
				"cycle"		"0.528571"
			}
			"trace"
			{
				"cycle"		"0.529999"
			}
			"trace"
			{
				"cycle"		"0.531428"
			}
			"trace"
			{
				"cycle"		"0.532856"
			}
			"trace"
			{
				"cycle"		"0.534285"
			}
			"trace"
			{
				"cycle"		"0.535714"
			}
			"trace"
			{
				"cycle"		"0.537142"
			}
			"trace"
			{
				"cycle"		"0.538570"
			}
			"trace"
			{
				"cycle"		"0.540000"
			}
			"trace"
			{
				"cycle"		"0.541428"
			}
			"trace"
			{
				"cycle"		"0.542856"
			}
			"trace"
			{
				"cycle"		"0.548570"
			}
			"trace"
			{
				"cycle"		"0.554285"
			}
			"trace"
			{
				"cycle"		"0.559999"
			}
			"trace"
			{
				"cycle"		"0.565713"
			}
			"trace"
			{
				"cycle"		"0.571429"
			}
			"trace"
			{
				"cycle"		"0.590000"
			}
			"trace"
			{
				"cycle"		"0.608571"
			}
			"trace"
			{
				"cycle"		"0.625715"
			}
			"trace"
			{
				"cycle"		"0.642858"
			}
			"trace"
			{
				"cycle"		"0.660001"
			}
			"trace"
			{
				"cycle"		"0.688573"
			}
			"trace"
			{
				"cycle"		"0.717146"
			}
			"trace"
			{
				"cycle"		"0.745717"
			}
			"trace"
			{
				"cycle"		"0.767146"
			}
			"trace"
			{
				"cycle"		"0.794289"
			}
			"trace"
			{
				"cycle"		"0.865719"
			}
			"trace"
			{
				"cycle"		"0.907148"
			}
			"trace"
			{
				"cycle"		"0.935721"
			}
			"trace"
			{
				"cycle"		"0.970007"
			}
		}
	}
}
