"tracers"
{
	"metadata"
	{
		"command"		"bb_tracerrecord Pure ACT_BB_B_RIGHT_T3 0.4 0.9"
	}
	"pure"
	{
		"ACT_BB_B_RIGHT_T3"
		{
			"trace"
			{
				"cycle"		"0.400001"
			}
			"trace"
			{
				"cycle"		"0.402309"
			}
			"trace"
			{
				"cycle"		"0.404616"
			}
			"trace"
			{
				"cycle"		"0.406924"
			}
			"trace"
			{
				"cycle"		"0.409232"
			}
			"trace"
			{
				"cycle"		"0.411540"
			}
			"trace"
			{
				"cycle"		"0.413847"
			}
			"trace"
			{
				"cycle"		"0.416155"
			}
			"trace"
			{
				"cycle"		"0.419231"
			}
			"trace"
			{
				"cycle"		"0.422309"
			}
			"trace"
			{
				"cycle"		"0.426924"
			}
			"trace"
			{
				"cycle"		"0.431540"
			}
			"trace"
			{
				"cycle"		"0.435386"
			}
			"trace"
			{
				"cycle"		"0.438462"
			}
			"trace"
			{
				"cycle"		"0.441539"
			}
			"trace"
			{
				"cycle"		"0.444616"
			}
			"trace"
			{
				"cycle"		"0.447693"
			}
			"trace"
			{
				"cycle"		"0.451540"
			}
			"trace"
			{
				"cycle"		"0.456155"
			}
			"trace"
			{
				"cycle"		"0.460770"
			}
			"trace"
			{
				"cycle"		"0.464616"
			}
			"trace"
			{
				"cycle"		"0.468463"
			}
			"trace"
			{
				"cycle"		"0.473078"
			}
			"trace"
			{
				"cycle"		"0.477694"
			}
			"trace"
			{
				"cycle"		"0.483847"
			}
			"trace"
			{
				"cycle"		"0.493078"
			}
			"trace"
			{
				"cycle"		"0.500771"
			}
			"trace"
			{
				"cycle"		"0.505385"
			}
			"trace"
			{
				"cycle"		"0.509232"
			}
			"trace"
			{
				"cycle"		"0.512309"
			}
			"trace"
			{
				"cycle"		"0.515385"
			}
			"trace"
			{
				"cycle"		"0.517693"
			}
			"trace"
			{
				"cycle"		"0.520000"
			}
			"trace"
			{
				"cycle"		"0.522308"
			}
			"trace"
			{
				"cycle"		"0.524616"
			}
			"trace"
			{
				"cycle"		"0.526155"
			}
			"trace"
			{
				"cycle"		"0.527693"
			}
			"trace"
			{
				"cycle"		"0.529231"
			}
			"trace"
			{
				"cycle"		"0.530769"
			}
			"trace"
			{
				"cycle"		"0.531538"
			}
			"trace"
			{
				"cycle"		"0.532308"
			}
			"trace"
			{
				"cycle"		"0.533077"
			}
			"trace"
			{
				"cycle"		"0.533846"
			}
			"trace"
			{
				"cycle"		"0.534616"
			}
			"trace"
			{
				"cycle"		"0.535385"
			}
			"trace"
			{
				"cycle"		"0.536154"
			}
			"trace"
			{
				"cycle"		"0.536923"
			}
			"trace"
			{
				"cycle"		"0.537693"
			}
			"trace"
			{
				"cycle"		"0.538462"
			}
			"trace"
			{
				"cycle"		"0.540000"
			}
			"trace"
			{
				"cycle"		"0.541539"
			}
			"trace"
			{
				"cycle"		"0.543077"
			}
			"trace"
			{
				"cycle"		"0.544615"
			}
			"trace"
			{
				"cycle"		"0.546154"
			}
			"trace"
			{
				"cycle"		"0.551538"
			}
			"trace"
			{
				"cycle"		"0.557692"
			}
			"trace"
			{
				"cycle"		"0.563846"
			}
			"trace"
			{
				"cycle"		"0.570768"
			}
			"trace"
			{
				"cycle"		"0.579230"
			}
			"trace"
			{
				"cycle"		"0.589999"
			}
			"trace"
			{
				"cycle"		"0.603075"
			}
			"trace"
			{
				"cycle"		"0.612305"
			}
			"trace"
			{
				"cycle"		"0.619229"
			}
			"trace"
			{
				"cycle"		"0.625382"
			}
			"trace"
			{
				"cycle"		"0.633075"
			}
			"trace"
			{
				"cycle"		"0.634613"
			}
			"trace"
			{
				"cycle"		"0.636151"
			}
			"trace"
			{
				"cycle"		"0.637690"
			}
			"trace"
			{
				"cycle"		"0.639228"
			}
			"trace"
			{
				"cycle"		"0.640766"
			}
			"trace"
			{
				"cycle"		"0.642305"
			}
			"trace"
			{
				"cycle"		"0.643843"
			}
			"trace"
			{
				"cycle"		"0.645382"
			}
			"trace"
			{
				"cycle"		"0.646920"
			}
			"trace"
			{
				"cycle"		"0.648459"
			}
			"trace"
			{
				"cycle"		"0.649997"
			}
			"trace"
			{
				"cycle"		"0.651535"
			}
			"trace"
			{
				"cycle"		"0.653074"
			}
			"trace"
			{
				"cycle"		"0.654612"
			}
			"trace"
			{
				"cycle"		"0.656920"
			}
			"trace"
			{
				"cycle"		"0.659228"
			}
			"trace"
			{
				"cycle"		"0.661536"
			}
			"trace"
			{
				"cycle"		"0.663843"
			}
			"trace"
			{
				"cycle"		"0.666150"
			}
			"trace"
			{
				"cycle"		"0.668458"
			}
			"trace"
			{
				"cycle"		"0.669996"
			}
			"trace"
			{
				"cycle"		"0.671535"
			}
			"trace"
			{
				"cycle"		"0.673074"
			}
			"trace"
			{
				"cycle"		"0.674612"
			}
			"trace"
			{
				"cycle"		"0.676151"
			}
			"trace"
			{
				"cycle"		"0.677689"
			}
			"trace"
			{
				"cycle"		"0.679227"
			}
			"trace"
			{
				"cycle"		"0.680765"
			}
			"trace"
			{
				"cycle"		"0.682304"
			}
			"trace"
			{
				"cycle"		"0.683842"
			}
			"trace"
			{
				"cycle"		"0.685381"
			}
			"trace"
			{
				"cycle"		"0.687689"
			}
			"trace"
			{
				"cycle"		"0.689996"
			}
			"trace"
			{
				"cycle"		"0.692303"
			}
			"trace"
			{
				"cycle"		"0.698457"
			}
			"trace"
			{
				"cycle"		"0.706149"
			}
			"trace"
			{
				"cycle"		"0.713842"
			}
			"trace"
			{
				"cycle"		"0.722303"
			}
			"trace"
			{
				"cycle"		"0.728457"
			}
			"trace"
			{
				"cycle"		"0.734610"
			}
			"trace"
			{
				"cycle"		"0.739995"
			}
			"trace"
			{
				"cycle"		"0.745379"
			}
			"trace"
			{
				"cycle"		"0.751533"
			}
			"trace"
			{
				"cycle"		"0.759225"
			}
			"trace"
			{
				"cycle"		"0.768456"
			}
			"trace"
			{
				"cycle"		"0.779224"
			}
			"trace"
			{
				"cycle"		"0.793839"
			}
			"trace"
			{
				"cycle"		"0.810762"
			}
			"trace"
			{
				"cycle"		"0.826915"
			}
			"trace"
			{
				"cycle"		"0.853838"
			}
			"trace"
			{
				"cycle"		"0.887683"
			}
		}
	}
}
